### ISSUE TITLE
On Mobile view text is overlapping on Confirmation Page

### ISSUE THREAD

**Issue by mivajenn** [mivaecommerce/readytheme-optics#11]
Where it says 
Product                   Quantity      Price   Subtotal

Also Subtotal gets cut off.

![screen shot 2016-09-15 at 10 10 54 am 2](https://cloud.githubusercontent.com/assets/11448089/18559576/b948a0fa-7b2c-11e6-916d-06c069c820d4.png)

**Comment by influxweb** [comment]
I am unable to duplicate this on the demonstration site. Can you test it there and let me know if you see the same results?

**Comment by mivajenn** [comment]
Here is the difference between your store and Brennan's - yours doesn't have all the info that Brennan's does - so you're not seeing it. Yours is the left, Brennan's is on the right.

![screen shot 2016-09-15 at 11 01 22 am 2](https://cloud.githubusercontent.com/assets/11448089/18561220/d90823be-7b33-11e6-8e5d-530dc20df2c1.png)

**Comment by mivajenn** [comment]
Ok, loaded it in my 96 store and it looks fine.

![screen shot 2016-09-15 at 11 10 49 am 2](https://cloud.githubusercontent.com/assets/11448089/18561529/20817654-7b35-11e6-8117-3850c203485c.png)
