### ISSUE TITLE
check out page in Optics should match checkout page in levels.

### ISSUE THREAD

**Issue by mivajenn** [mivaecommerce/readytheme-optics#6]
The saved cards are contained in a box

OPTICS
![screen shot 2016-09-14 at 3 16 48 pm](https://cloud.githubusercontent.com/assets/11448089/18532096/c042d00e-7a8e-11e6-9213-f0ae658290b9.png)

LEVELS
![levels-checkout](https://cloud.githubusercontent.com/assets/11448089/18532154/1aa607dc-7a8f-11e6-8cc7-a1eeb15fa885.png)

**Comment by influxweb** [comment]
I'm not sure that matters since they are different frameworks. Levels doesn't looks like Storyteller or Booc either.

**Comment by mivajenn** [comment]
He meant that he wants the MivaPay to match - put the payment options in a box like levels. Sorry for confusion.

**Comment by influxweb** [comment]
This has been updated.
