### ISSUE TITLE
Non-Miva Pay Methods need formatting

### ISSUE THREAD

**Issue by bheyde** [mivaecommerce/readytheme-optics#9]
When you have a non-MivaPay payment method they are showing the payment icon and the radio button. I think previously it only showed the payment icon

![image](https://cloud.githubusercontent.com/assets/766816/18557075/5391e19a-7b22-11e6-9b75-12620050dbf5.png)

**Comment by influxweb** [comment]
This should be fixed with the updates made for issue #6
